### ISSUE TITLE
expickr GREAT + Question: read changed EXCEL file back into R?

### ISSUE THREAD

**Issue by sfd99** [jooyoungseo/ezpickr#1]
**Hi JooYoung,**

expickr is GREAT 
and _very_ useful.

**+ Question:** 

How to read a changed EXCEL file 
back into R?.

**example:**
**1)**  I do: 
     viewxl(airquality)

**2)**  In Excel / LibreOffice CALC in Linux
    I magically see the airquality DF. 
    Super!.

**3)**  In the first Row of the spreadsheet,
     I change the OZONE value 
     from: 41
     to:     44.

 **4)**  I do: CTRL+S 
      to Save the changed spreadsheet file.

**Q:**
How do I now _see_
the _changed_ airquality DF 
back in my Rstudio Console,
with the _new OZONE value_ (ie: 44 instead of 41) ?.

(In the Rstudio Console,
 when I type: airquality, 
 I still see the old OZONE value: 41...unchanged DF).

What are the **steps**, please?.

Thanks!.
**SFd99
San Francisco
R 4.2.1 , Rstudio (latest version) 
Ubuntu Linux 20.04
LibreOffice 6.4.7.2
EZpickr v. 2.1.0**

**Comment by jooyoungseo** [comment]
Thanks for your kind words, @sfd99.

Try with the following:

``` r
airquality2 <- ezpickr::viewxl(airquality)
# Change anything in your spread sheet and press ctrl+s to save.
# In R console, just press enter if you are asked to provide any file name.
# the new object `airquality2` contains all the changes you have made.
airquality2
```
Hope this helps.

**Comment by sfd99** [comment]
Yes, works!.

Thank you so much 
for your clear explanation, JooYoung.

Perfect!.
감사합니다

_**SFd99**_
